# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lj8O04CpytjhWsyDGxTgafMv5SOhBCG3
"""

#src/data_generation.py
import numpy as np
from sklearn.datasets import make_blobs

def generate_data(
    n_samples=500,
    centers=4,
    cluster_std=(1.0, 2.5, 1.5, 3.0),
    random_state=42
):
    X, y_true = make_blobs(
        n_samples=n_samples,
        centers=centers,
        cluster_std=cluster_std,
        random_state=random_state
    )
    return X, y_true

if __name__ == "__main__":
    X, y = generate_data()
    print("Data shape:", X.shape)